services:

    tlconseil.systempay:
        class: Tlconseil\SystempayBundle\Service\SystemPay
        arguments: ["@doctrine.ormss.entity_manager", "@service_container"]

    tlconseil.systempay.twig_extension:
        class: Tlconseil\SystempayBundle\Twig\TwigExtension
        tags:
            - { name: twig.extension }
